http.host: 0.0.0.0
node.name: logstash-server
path.config: /usr/share/logstash/config.d
path.data: /usr/share/logstash/data
path.logs: /var/log/logstash
xpack.management.pipeline.id:
  - api-analytics-process
xpack.monitoring.elasticsearch.hosts: ${ELASTICSEARCH_URL}
xpack.monitoring.elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
xpack.monitoring.elasticsearch.username: ${ELASTICSEARCH_USERNAME}
xpack.monitoring.enabled: true
